version: "3.9"
services:
  api:
    container_name: Api
    build: ./Api
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
      - rabbitmq
  calculation:
    container_name: Calculation
    build: ./Calculation
    ports:
      - "6000:80"
      - "6001:443"
    depends_on:
      - rabbitmq
  db:
    container_name: database
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
      - "1434:1433"
    expose:  
      - "1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
     - 15672
     - 5672
    environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=password        