version: "3.9"
services:
  api:
    container_name: api
    build: 
      context: ./api
      target: tests
  calculation:
    container_name: calculation
    build: 
      context: ./calculation
      target: tests