version: "3.9"
services:
  # api:
  #   container_name: api
  #   build: ./api
  #   ports:
  #     - "5000:5000"
  #     - "5001:5001"
  #   depends_on:
  #     - db
  db:
    container_name: database
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
      - "1434:1433"
    expose:  
      - "1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"